# Generated by Django 6.0 on 2025-12-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='chief_complaint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='visit',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_primary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis_secondary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='visit',
            name='doctor_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='examination',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='history_of_present_illness',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='treatment_plan',
            field=models.TextField(blank=True),
        ),
    ]
