# Generated by Django 6.0 on 2025-12-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='hmo_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
