# Generated by Django 6.0 on 2025-12-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_hmo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmoclaimitem',
            name='dispute_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hmoclaimitem',
            name='disputed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hmoclaimitem',
            name='disputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='hmo_dispute_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='hmo_dispute_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='hmo_last_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='hmo_state',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('SUBMITTED', 'Submitted'), ('DISPUTED', 'Disputed'), ('APPROVED', 'Approved'), ('SETTLED', 'Settled')], default='OK', max_length=20),
        ),
    ]
