# Generated by Django 6.0 on 2025-12-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_hmofollowup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmofollowup',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('REINDED', 'Reminded'), ('ESCALATED', 'Escalated'), ('SETTLED', 'Settled')], default='OPEN', max_length=20),
        ),
    ]
