# Generated by Django 6.0 on 2025-12-13 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hmo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('other_names', models.CharField(blank=True, max_length=60)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='patients/passports/')),
                ('is_hmo', models.BooleanField(default=False)),
                ('hmo_id_number', models.CharField(blank=True, max_length=60)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=120)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=30)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('allergies', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hmo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hmo.hmo')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
